### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by timvahlbrock** [Oeffis/location-analyzer#1]
Setup project to get ready to perform actual implementation.
```[tasklist]
### Tasks
- [x] Create project
- [x] Integrate Time Tracking from main repo
- [x] ~~Integrate Issue Automation from main repo~~
- [x] Add documents
- [x] Create basic project structure
- [x] Setup basic pipeline
```

**Comment by timvahlbrock** [comment]
Time spent: 30 minutes

Spent on:
+ Create project
+ Integrate Time Tracking from main repo

**Comment by timvahlbrock** [comment]
Time spent: 1 hour

Spent on:
+ e1e733a7587a868a94b2cb79f422c1f831fe6675 add documents
+ f5c7e0d59c262e74ffd03e9fbd0e25d23d924d3a add package.json, .npmignore
+ 3e8658e6bd8c8d9f7c888cd3d20bde624ee914fb install typescript, eslint, eslint plugins
+ 4f4b200af376b5e72f8e27f7e7fb9b526870fdb6 add sample source file
+ 7e2833afb739d0d75c1eac5efca697c8a2356911 add npm scripts
+ 3607154dfd5b1cf047669bec982cea6d4dfabe72 add eslint config, ts config
+ 47924013e675352f6ca273a06e3c735e789c6d0f make eslint ignore dist and node_modules
+ 0577485446bf6b9b76ec96f7f3b3120bbaa222cb add cucumber
+ 6c9417055ede669a74d46d2d682f9f6f562d6b4a add basic ci
+ c21c65d26100a174886a7669f2406094372a8b85 remove working-directory entries from ci
+ bab25bd0475d1c74f5329a9dd492fa4a012fef0e add feature files
+ e0a5721c5067afaa277b0f7570e48e53e9cf3906 disable feature files for now

**Comment by timvahlbrock** [comment]
@WConen this is the repository where I will perform the implementations.

**Comment by timvahlbrock** [comment]
Time spent: 30 minutes

Spent on:
+ creating milestones and issues

**Comment by timvahlbrock** [comment]
Time spent: 30 minutes

Spent on:
+ 5b3915829d1fc8fe3d128d99126582a2ca7a0fc5 add stryker (mutation testing) configuration
+ 638daf38692df4a69b8b9a13bef51dbc0a9c88cd run stryker in pipeline
+ cde8bdf7dbf5df4edbc9376dd8cbb4621a700e7a add build artifacts
