### ISSUE TITLE
Integrate VRR Data (stops)

### ISSUE THREAD

**Issue by timvahlbrock** [Oeffis/location-analyzer#2]
```[tasklist]
### Tasks
- [x] get data
- [x] structure/filter data
- [x] make data available to application
- [x] ~~access real time data~~ (can be delayed till train detection)
- [x] evaluate storing data on server, anonymisation strategies
```

**Comment by timvahlbrock** [comment]
Time spent: 2 hours

Spent on:
+ 9d36eda634765038202674ac0f27bbef47ecfb99 add raw stops file
+ 5167b7ffcab99feff99080007e2ee1e599b5fe35 add and transform vrr stops
+ 7986afc89c89eed484f678892fbf7d4ce83d0146 add column names to csv, improve file name

**Comment by timvahlbrock** [comment]
Regarding anonymised access from server: When the stop information is reduced to the required columns and zipped using pako, the size is reduced to 390 KB for ALL the stops of the VRR. This should be okay for a one time operation. So potentially anonymity could be achieved by always loading all the data.
