### ISSUE TITLE
Determine nearby platforms

### ISSUE THREAD

**Issue by timvahlbrock** [Oeffis/location-analyzer#4]
Determine nearby platforms by combining departure and location data

```[tasklist]
### Features
- [x] Detect nearby platform
- [x] Detect multiple nearby platforms
- [x] Detect no platform if not present
- [x] Detect that person is on platform (distance should be zero)
```

```[tasklist]
### Tasks
- [x] Refactoring
- [x] Integrate alternative data sources, if applicable
- [x] Real life testing
```

**Comment by timvahlbrock** [comment]
Time spent: 1,5 hours

Spent on:
+ c304380a8a75a080219ca6a16bc94951fc9e8d03 add first basic stub implementation

**Comment by timvahlbrock** [comment]
Time spent: 1 hour 30 minutes

Spent on:
+ c304380a8a75a080219ca6a16bc94951fc9e8d03 add first basic stub implementation
+ 729fe067373305276b346820c7f0e1f18d99dee3 fix linting error

**Comment by timvahlbrock** [comment]
Time spent: 2 hours

Spent on:
+ df7271e1d94850af6b0e97c9fc1c178d82dceb4c get stopps by actually calculating distance
+ 28156d6a4d0aca912cf2a1336370e466eae5ba96 improve test case structure
+ 20ceb77f14c6c87c1cbbfafe2546a7df949a18b5 refactor location analyser to own class
+ 9c62c63dbb321e97e43a314c8b622aa33206f379 keep current location in location analyzer instead of world
+ 1644137c9e1a8fe28ad9526495a1ff16741bf7fc add scenario where no location was set
+ 1221f035c587e2093b3a9a2ae46b1764ad6eae0a add assertion of distance is 0 when exactly at platform
+ be5d5c57fadc8d3cea8323e380184c0a25a3b3fc (wip) add test to get nearest stop when in proximity

**Comment by timvahlbrock** [comment]
Time spent: 1 hour 30 minutes

Spent on:
+ 61cc86b9984e512ed1e2a292e94e3c9e71d4f72d calculate distance accurately
+ 5a356e823a399f0648840fba095c3243f9d9eb2d remove duplicate test
+ 3b374818501baa0425150f4fedf4e57ada319332 add test for multiple platforms

**Comment by timvahlbrock** [comment]
Time spent: 1 hour

Spent on:
+ 1ec33718c7ba6404548dc8b8b6bbfcdc799c7768 cache status calculation
+ 343f82b2442bcaca9ed59cb731050f3d0bbc0f9e add extension recommendations
+ 9afe3aa1ef0f453ce8c2a894ba40bc6d382f4835 add test for no stops added (mutations survived)
+ e4a6d4b7625431c06388a22afd747ba3adf379b1 Add test for adding stops later (mutations survived)
+ 153a22638796be71f75b95f83fab6031f95521be remove currently unnecessary parent field
+ b7bceb525f5413b5748d336bee51619d5ca2d153 Added a test for updated locations (mutations survived)
+ 145de0f25d08f9454b35bca60df70ca85603f22b switched background fraise to use forVRR factory method
+ 135e8fc2339a8e7c3b94c0c94822d042c22e6a4a align capitalization of forVRR factory method

**Comment by timvahlbrock** [comment]
As described in https://github.com/Oeffis/location-analyser/issues/3#issuecomment-1806011463 , the search for alternative data sources to detect stops is suspended for now.

**Comment by timvahlbrock** [comment]
Time spent: 2 hours

Spent on:
+ be5ffc84d455b51094d0fd617205d8b386dc7005 create better project separation
+ 12843d7cb3ac95164c36f460704a8f42b8d47949 create better project separation

as prework to create a test app

**Comment by timvahlbrock** [comment]
Time spent: 3 hours

Spent on:
+ 4ea42d29360cfe586a0706fb44d07910735bb8e1 remove redundant App.test.tsx
+ 19075fd3ed3becd19905d4d23419a4f5eaa9e2f8 move features into location-analyzer folder
+ 35e6b891b8a02e6ca5ed347e87598a51e2f7ce16 include tsx in linting
+ f7fe1afec42e5d58576c69f8dd03ea048cbcd831 install @capacitor/geolocation in demo project
+ e9d320688ddf75f4e43c4ffeccc8e8dae36a5293 show basic location information in demo app
+ 3a2de820f8fc9f2684afd2f91f918809a4041c2b (wip) include location analyzer in demo app
+ 199c86f2d17d6c319f69d87e38a807d85f76d70f make vrr stops part of testing to make location analyser runtim independent
+ b5013fa2122a7a8e8b8253d3a1fa7e3b6cc001ee include vrr stops in demo
+ 1b8a01b20fa28f556df736521ff3cd99c3d44b1c fix error in beacon script
+ aec5311254fbbb88a72749ba6313907bc42d6fb5 fix call of gone factory method in stepDefinitions

**Comment by timvahlbrock** [comment]
Time spent: 1 hour

spent on:
+ 21b6b6eb2e8a9e9a8026dd2711647e1cb861e165 Improve demo

**Comment by timvahlbrock** [comment]
Testing has shown, that the single pair of coordinates per platform isn't enough to reliably determine the platform. Luckily, openstreetmap has boundaries for each platform, including information about the platform names. However, in the available downloads this data is buried within all other data available from osm. The commits mentioned below extract that data from the main osm dataset for further processing.

Time spent: 8 hours

Spent on:
+ 0d6fdefc65f60d88fcbefa2e430dde2452f0f1b1 extract platforms from osm data
+ e6474ba7a77d39dc02a3e7be7e4b7f686c907491 extract nodes from osm data
+ 45841d55535e92fa6b3ba538803c068e1e6784d1 only extract notes that are present in ways

**Comment by timvahlbrock** [comment]
Closing this as completed for now. Might pick-up on OSM data later.

**Comment by timvahlbrock** [comment]
Time spent: 2 hours

Spent on:
+ 403edf4b090bec11666b9611c3a3c01d5f986d09 Lib, Scripts: use csv to stringify and parse, add implementation and adapt tests for platform as bounds implementation

**Comment by timvahlbrock** [comment]
Time spent: 10 minutes

Spent on:
+ f5934ea9d325ac5a92383da3bba7613f91cb9823 Lib: make distance 0 when on platform
